{...}: {
  imports = [
    ./bat.nix
    ./browsers
    ./cursor-editor.nix
    ./fastfetch.nix
    ./fonts.nix
    ./fzf.nix
    ./git.nix
    ./ghostty.nix
    ./legcord
    ./llm.nix
    ./micro.nix
    ./nvim.nix
    ./nh.nix
    ./obs-studio.nix
    ./p10k/p10k.nix
    ./packages.nix
    ./spicetify.nix
    ./ssh.nix
    ./simple-bar.nix
    ./stylix.nix
    ./tigervnc.nix
    ./ubersicht.nix
    ./vscode
    ./worktrunk.nix
    ./zed-editor.nix
    ./zsh
  ];
}
